'use strict';
const DEMO=window.CRM_DEMO===true,STORE='andrina-crm-demo-v1';
const STATUS=['Pendiente','En curso','En revisión','Bloqueada','Completada'],STAGES=['Idea','Guion','Producción','Diseño / Edición','Revisión interna','Cliente','Correcciones','Aprobado','Programado','Publicado'];
let state=null,view='dashboard',query='',clientFilter='',ownerFilter='',statusFilter='',display='board',focusId=null,detailTab='ficha',cal=new Date(),poll=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID(),today=()=>localDate(new Date());
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayOffset(n){let d=new Date();d.setDate(d.getDate()+n);return localDate(d)}
function pretty(d){return d?new Date(d+'T12:00:00').toLocaleDateString('es-AR',{day:'numeric',month:'short'}):'Sin fecha'}
function stamp(d){return new Date(d).toLocaleString('es-AR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}
function initials(n){return String(n||'?').split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()}
function avatar(n,url=''){return `<span class="avatar">${url?`<img src="${esc(url)}" alt="${esc(n)}">`:esc(initials(n))}</span>`}
function client(id){return state.clients.find(c=>c.id===id)||{name:'Cliente'}}
function owner(id){return state.users.find(u=>u.id===id)||{name:'Responsable'}}
const done=t=>t.status==='Completada',admin=()=>state.user.role==='admin';
function badge(v){return `<span class="badge ${['Crítico','Bloqueada'].includes(v)?'red':['Prioritario','Correcciones'].includes(v)?'orange':['En revisión','Cliente','Contenido'].includes(v)?'purple':['Planificable','Completada'].includes(v)?'gray':''}">${esc(v)}</span>`}
function opts(list,selected){return list.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('')}
function entityOpts(list,selected){return list.map(v=>`<option value="${esc(v.id)}" ${v.id===selected?'selected':''}>${esc(v.name)}</option>`).join('')}
function notify(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',5500)}
function seed(){
 const users=[{id:'a',name:'Andrina',email:'andri@ejemplo.com',role:'admin',active:1},{id:'b',name:'Sofía · ejemplo',email:'sofi@ejemplo.com',role:'team',active:1},{id:'c',name:'Martina · ejemplo',email:'marti@ejemplo.com',role:'team',active:1}];
 const clients=[{id:'che',name:'Chetech',plan:'Ejemplo · Gestión de redes',memory:'Ejemplo editable. Diagnóstico sin cargo. Retiro a domicilio en Río Tercero.',contact:'',startDate:today(),notes:''},{id:'paj',name:'Pajtman',plan:'Ejemplo · Contenido mensual',memory:'Ejemplo editable. Mantener tono claro y cercano. Revisión profesional antes de publicar.',contact:'',startDate:today(),notes:''},{id:'bil',name:'Expreso Biletta',plan:'Ejemplo · Redes y contenido',memory:'Ejemplo editable. Kilómetros de confianza. Cercanía, equipo y logística.',contact:'',startDate:today(),notes:''},{id:'up',name:'Up! Mini Eventos',plan:'Ejemplo · Gestión de redes',memory:'Ejemplo editable. Espacio para eventos infantiles, zona Montessori y cocina propia.',contact:'',startDate:today(),notes:''}];
 const titles=['Editar reel del taller','Diseñar carrusel educativo','Preparar copy para LinkedIn','Planificar grabación del salón','Revisar guion de servicio técnico','Armar propuesta de contenido'];
 const tasks=titles.map((title,i)=>({id:'t'+i,title,clientId:clients[i%4].id,assigneeId:users[i%3].id,kind:i===5?'Tarea':'Contenido',status:STATUS[i%5],stage:['Diseño / Edición','Guion','Revisión interna','Producción','Aprobado','Idea'][i],priority:i===0?'Prioritario':'Planificable',priorityReason:i===0?'Ejemplo: fecha de campaña acordada.':'',due:dayOffset(i-1),publishDate:dayOffset(i+2),description:'Dato de demostración. Reemplazá este brief por el trabajo real.',script:'',copy:'',format:i%2?'Carrusel':'Reel',platform:'Instagram',blocker:i===3?'Ejemplo: faltan imágenes del cliente.':'',links:[],rounds:0,roundLimit:2,version:1}));
 return {user:users[0],users,clients,tasks,comments:[],activity:[],settings:{name:'Andrina Studio',accent:'#d9f36a',secondary:'#c8b8f2',avatar:''},csrf:'demo'};
}
let fullDemo;
function demoState(){const s=structuredClone(fullDemo),u=s.users.find(x=>x.id===fullDemo.currentUser)||s.users[0];s.user=u;if(u.role!=='admin'){s.tasks=s.tasks.filter(t=>t.assigneeId===u.id);s.clients=s.clients.filter(c=>s.tasks.some(t=>t.clientId===c.id));s.clients=s.clients.map(c=>({id:c.id,name:c.name,plan:c.plan,memory:c.memory}));s.users=s.users.filter(x=>x.id===u.id);s.comments=s.comments.filter(c=>s.tasks.some(t=>t.id===c.task_id));s.activity=s.activity.filter(c=>s.tasks.some(t=>t.id===c.task_id))}return s}
function saveDemo(){try{localStorage.setItem(STORE,JSON.stringify(fullDemo))}catch{notify('Este navegador no permite guardar la demo. Los cambios durarán solo esta sesión.')}state=demoState()}
async function api(path,method='GET',body){
 if(DEMO){
  if(path==='/api/state')return demoState();
  if(path==='/api/export')return fullDemo;
  const parts=path.split('/'),key=parts[2],itemid=parts[3];
  if(key==='comments'){fullDemo.comments.push({id:id(),task_id:body.taskId,user_id:state.user.id,text:body.text,created:new Date().toISOString(),author:state.user.name})}
  else if(key==='settings'){fullDemo.settings=body}
  else if(key==='users'){if(method==='POST')fullDemo.users.push({id:id(),name:body.name,email:body.email,role:'team',active:1});else {const clean={...body};delete clean.password;Object.assign(fullDemo.users.find(u=>u.id===itemid),clean);}}
  else if(['tasks','clients'].includes(key)){
   let arr=fullDemo[key];if(method==='DELETE')fullDemo[key]=arr.filter(x=>x.id!==itemid);else if(method==='POST'){let item={...body,id:id(),version:1};arr.push(item);if(key==='tasks')demoLog(item,'Creó la tarea')}
   else {let idx=arr.findIndex(x=>x.id===itemid);if(key==='tasks'&&arr[idx].version!==body.version)throw Error('Otra pestaña modificó la tarea. Recargá.');arr[idx]={...body,id:itemid,version:(arr[idx].version||0)+1};if(key==='tasks')demoLog(arr[idx],'Actualizó la tarea')}
  }
  saveDemo();return {ok:true};
 }
 let r=await fetch(path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-CSRF-Token':state?.csrf||''},body:body?JSON.stringify(body):undefined});
 const d=await r.json();if(!r.ok){if(r.status===401&&path!=='/api/login'){clearInterval(poll);state=null;login()}throw Error(d.error||'No pudimos completar la acción.')}return d;
}
function demoLog(t,text){fullDemo.activity.unshift({id:id(),task_id:t.id,author:state.user.name,text,created:new Date().toISOString()})}
async function refresh(render=true){state=await api('/api/state');if(render)draw()}
function login(){
 $('#app').innerHTML=`<div class="login"><div class="login-art"><div class="brand"><span class="symbol">✳</span> Andrina Studio</div><div><span class="eyebrow">Tu espacio de operaciones</span><h1>Más claridad.<br>Más espacio<br>para crear.</h1><p>Clientes, contenido y equipo.<br>Todo en el mismo lugar.</p></div><small>Un estudio organizado empieza acá.</small></div><div class="login-form"><h2>Qué bueno verte.</h2><p class="muted">Ingresá con tu cuenta del equipo.</p><form id="login-form"><label>Email</label><input name="email" type="email" autocomplete="username" required><label>Contraseña</label><input name="password" type="password" autocomplete="current-password" required><p class="err" id="login-error" role="alert"></p><button class="btn lime">Entrar a operaciones →</button></form><p class="notice">El acceso de clientes se habilitará en una próxima etapa.</p></div></div>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{await api('/api/login','POST',Object.fromEntries(new FormData(e.target)));await refresh();startPoll()}catch(err){$('#login-error').textContent=err.message}finally{btn.disabled=false}};
}
const navItems=[['dashboard','◈','Resumen'],['tasks','☷','Tareas'],['mine','◉','Mi trabajo'],['content','▧','Contenido'],['calendar','▦','Calendario'],['clients','◇','Clientes'],['team','♧','Equipo'],['portal','↗','Portal de clientes'],['settings','⚙','Configuración']];
function draw(){
 document.documentElement.style.setProperty('--lime',state.settings.accent);document.documentElement.style.setProperty('--lav',state.settings.secondary);
 const nav=navItems.filter(([k])=>admin()||!['team','settings'].includes(k));
 $('#app').innerHTML=`${DEMO?`<div class="demo-bar"><span>DEMO · ejemplos ficticios · datos guardados solo en este navegador</span><select id="demo-user" aria-label="Probar como">${entityOpts(fullDemo.users.filter(u=>u.active),state.user.id)}</select><button data-action="reset-demo">Restablecer ejemplos</button></div>`:''}<div class="shell"><aside class="sidebar"><div class="brand"><span class="symbol">✳</span>${esc(state.settings.name)}</div><div><div class="eyebrow">Espacio de trabajo</div><nav class="nav">${nav.map(([k,ico,name])=>`<button data-view="${k}" class="${view===k?'active':''}"><span class="ico" aria-hidden="true">${ico}</span>${name}</button>`).join('')}</nav></div><div class="side-bottom"><div class="person">${avatar(state.user.name,admin()?state.settings.avatar:'')}<div>${esc(state.user.name)}<br><small>${admin()?'Administración':'Equipo creativo'}</small></div></div><button class="mini-btn" data-action="logout" style="margin-top:16px">${DEMO?'Demo sin contraseña':'Cerrar sesión'}</button></div></aside><main class="main"><header class="topbar"><span class="breadcrumb">Espacio de trabajo / ${navItems.find(x=>x[0]===view)?.[2]||'Resumen'}</span><div class="toolbar"><input class="search" id="search" placeholder="Buscar tareas o clientes…" aria-label="Buscar" value="${esc(query)}">${avatar(state.user.name,admin()?state.settings.avatar:'')}</div></header><section id="surface">${surface()}</section></main></div>`;
 $('#search').addEventListener('input',e=>{query=e.target.value;$('#surface').innerHTML=surface()});if(DEMO)$('#demo-user').onchange=async e=>{fullDemo.currentUser=e.target.value;saveDemo();view='dashboard';resetFilters();draw()};
}
function resetFilters(){query='';clientFilter='';ownerFilter='';statusFilter=''}
function head(title,sub,button=''){return `<div class="welcome"><div><h1>${title}</h1><p>${sub}</p></div>${button}</div>`}
function newTaskBtn(){return admin()?'<button class="btn lime" data-action="new-task">＋ Nueva tarea</button>':''}
function filtered(){return state.tasks.filter(t=>(!query||[t.title,t.description,client(t.clientId).name].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!clientFilter||t.clientId===clientFilter)&&(!ownerFilter||t.assigneeId===ownerFilter)&&(!statusFilter||(statusFilter==='__late'?(!done(t)&&t.due&&t.due<today()):t.status===statusFilter))&&(view!=='mine'||t.assigneeId===state.user.id)&&(view!=='content'||t.kind==='Contenido'))}
function row(t){return `<button class="task-row" data-task="${esc(t.id)}"><span class="square">${t.kind==='Contenido'?'▧':'✓'}</span><span class="info"><strong>${esc(t.title)}</strong><small>${esc(client(t.clientId).name)} · ${esc(owner(t.assigneeId).name)} · ${pretty(t.due)}</small></span>${badge(t.status)}</button>`}
function dashboard(){
 const open=state.tasks.filter(t=>!done(t)),late=open.filter(t=>t.due&&t.due<today()),review=open.filter(t=>t.status==='En revisión'),block=open.filter(t=>t.status==='Bloqueada');
 const agenda=[...open].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).slice(0,5);
 return head(`Hola, ${esc(state.user.name.split(' ')[0])}.`,'Un vistazo a tu estudio, para empezar con claridad.',newTaskBtn())+`<div class="hero"><div><span class="eyebrow">Todo en su lugar</span><h2>${late.length?'Hay pendientes que necesitan una mirada.':open.length?'Tu equipo tiene una hoja de ruta.':'Hagamos espacio para lo que viene.'}</h2><p>${open.length} tareas abiertas · ${review.length} en revisión · ${block.length} bloqueadas</p></div><span class="hero-mark" aria-hidden="true">✳</span></div><div class="stats">${[[open.length,'Tareas abiertas','tasks'],[late.length,'Fuera de fecha','late'],[review.length,'Para revisar','review'],[state.clients.length,'Clientes activos','clients']].map(([n,label,key])=>`<button class="stat" data-stat="${key}"><small>${label}<em>↗</em></small><strong>${n}</strong></button>`).join('')}</div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>Primero, lo importante</h3><button class="muted" data-view="tasks">Ver tareas →</button></div>${agenda.map(row).join('')||'<div class="empty">Todavía no hay tareas. Creá tu primer cliente y asigná trabajo al equipo.</div>'}</div><div class="side-stack"><div class="panel"><div class="panel-head"><h3>Clientes que necesitan atención</h3></div><div class="panel-body">${state.clients.filter(c=>state.tasks.some(t=>t.clientId===c.id&&!done(t)&&(t.status==='Bloqueada'||t.status==='En revisión'||(t.due&&t.due<today())))).map(c=>`<button class="attention" data-client="${c.id}" style="width:100%;text-align:left">${avatar(c.name)}<div><h3>${esc(c.name)}</h3><p>${state.tasks.filter(t=>t.clientId===c.id&&t.status==='Bloqueada').length} bloqueadas · ${state.tasks.filter(t=>t.clientId===c.id&&t.status==='En revisión').length} en revisión</p></div></button>`).join('')||'<p class="muted">Sin alertas por el momento.</p>'}</div></div><div class="panel"><div class="panel-head"><h3>La carga del equipo</h3></div><div class="panel-body">${state.users.filter(u=>u.active).map(u=>{const ts=state.tasks.filter(t=>t.assigneeId===u.id),complete=ts.filter(done).length;return `<div style="margin-bottom:14px"><div class="person">${avatar(u.name)}<div><strong style="font-size:12px">${esc(u.name)}</strong><div class="load">${ts.length-complete} abiertas · ${complete} terminadas</div></div></div><div class="progress"><span style="width:${ts.length?complete/ts.length*100:0}%"></span></div></div>`}).join('')}</div></div></div></div>`;
}
function filters(){return `<div class="filters"><select id="client-filter" aria-label="Cliente"><option value="">Todos los clientes</option>${entityOpts(state.clients,clientFilter)}</select>${admin()?`<select id="owner-filter" aria-label="Responsable"><option value="">Todo el equipo</option>${entityOpts(state.users,ownerFilter)}</select>`:''}<select id="status-filter" aria-label="Estado"><option value="">Todos los estados</option><option value="__late" ${statusFilter==='__late'?'selected':''}>Fuera de fecha</option>${opts(STATUS,statusFilter)}</select><div class="toggle"><button data-display="board" class="${display==='board'?'active':''}">Tablero</button><button data-display="list" class="${display==='list'?'active':''}">Lista</button></div><button class="muted" data-action="clear-filters">Limpiar</button></div>`}
function taskCard(t){return `<button class="card" data-task="${t.id}">${badge(t.priority)}<p class="client">${esc(client(t.clientId).name)} · ${esc(t.kind)}</p><h3>${esc(t.title)}</h3>${t.kind==='Contenido'?`<p class="muted" style="font-size:10px;margin-bottom:12px">${esc(t.stage)}</p>`:''}<div class="card-footer"><span class="${t.due&&t.due<today()&&!done(t)?'danger-text':''}">${pretty(t.due)}</span>${avatar(owner(t.assigneeId).name)}</div></button>`}
function tasks(){let ts=filtered();return head(view==='content'?'Contenido':view==='mine'?'Mi trabajo':'Un equipo, una hoja de ruta.',view==='content'?'Desde la idea hasta la publicación.':'Asigná, avanzá y registrá cada paso.',newTaskBtn())+filters()+(display==='board'?`<div class="board">${STATUS.map(s=>`<div class="column"><div class="column-head"><span>${s}</span><span>${ts.filter(t=>t.status===s).length}</span></div>${ts.filter(t=>t.status===s).map(taskCard).join('')||'<p class="muted" style="text-align:center;font-size:11px;padding:15px">Sin tareas</p>'}</div>`).join('')}</div>`:`<div class="panel table-wrap"><table><thead><tr><th>Tarea</th><th>Cliente</th><th>Responsable</th><th>Entrega</th><th>Estado</th><th>Prioridad</th></tr></thead><tbody>${ts.map(t=>`<tr tabindex="0" data-task="${t.id}"><td>${esc(t.title)}</td><td>${esc(client(t.clientId).name)}</td><td>${esc(owner(t.assigneeId).name)}</td><td>${pretty(t.due)}</td><td>${badge(t.status)}</td><td>${badge(t.priority)}</td></tr>`).join('')}</tbody></table>${!ts.length?'<div class="empty">No hay tareas con estos filtros.</div>':''}</div>`)}
function calendar(){let year=cal.getFullYear(),month=cal.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-(first.getDay()+6)%7),days=[];for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let date=localDate(d),ts=filtered().filter(t=>(t.kind==='Contenido'&&t.publishDate?t.publishDate:t.due)===date);days.push(`<div class="day ${d.getMonth()!==month?'out':''} ${date===today()?'today':''}"><span class="date-num">${d.getDate()}</span>${ts.map(t=>`<button class="cal-task ${t.kind==='Tarea'?'task':''}" data-task="${t.id}" title="${esc(t.title)}">${esc(t.title)}<small>${esc(client(t.clientId).name)} · ${esc(t.kind==='Contenido'&&t.publishDate?'Publicación':'Entrega')}</small></button>`).join('')}</div>`)}return head('Tu calendario.','Contenido por fecha de publicación; tareas por fecha de entrega.',newTaskBtn())+`<div class="cal-top"><h2>${esc(cal.toLocaleDateString('es-AR',{month:'long',year:'numeric'}))}</h2><div class="toolbar"><button class="btn soft" data-cal="-1" aria-label="Mes anterior">←</button><button class="btn soft" data-cal="0">Hoy</button><button class="btn soft" data-cal="1" aria-label="Mes siguiente">→</button></div></div><div class="cal-outer"><div class="calendar">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(s=>`<div class="day-label">${s}</div>`).join('')}${days.join('')}</div></div>`}
function clients(){const cs=state.clients.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));return head('Tus clientes.','La información de cada marca, siempre a mano.',admin()?'<button class="btn lime" data-action="new-client">＋ Nuevo cliente</button>':'')+`<div class="cards">${cs.map(c=>{let ts=state.tasks.filter(t=>t.clientId===c.id);return `<button class="panel client-card" data-client="${c.id}">${avatar(c.name)}<h2>${esc(c.name)}</h2><p>${esc(c.plan||'Sin plan registrado')}</p><div class="progress"><span style="width:${ts.length?ts.filter(done).length/ts.length*100:0}%"></span></div><div class="card-footer"><span>${ts.filter(t=>!done(t)).length} tareas abiertas</span><span>Ver ficha ↗</span></div></button>`}).join('')}</div>${!cs.length?'<div class="empty">Creá el primer cliente para comenzar.</div>':''}`}
function team(){return head('El equipo.','Cada persona con su cuenta y sus tareas.', '<button class="btn lime" data-action="new-user">＋ Agregar integrante</button>')+`<div class="panel">${state.users.map(u=>`<div class="member">${avatar(u.name)}<div class="info"><h3>${esc(u.name)}</h3><p class="muted">${esc(u.email)} · ${u.role==='admin'?'Administración':'Equipo'} · ${u.active?'Activo':'Sin acceso'}</p></div><span class="badge gray">${state.tasks.filter(t=>t.assigneeId===u.id&&!done(t)).length} abiertas</span><button class="mini-btn" data-password="${u.id}">Cambiar contraseña</button>${u.id!==state.user.id?`<button class="mini-btn" data-user-toggle="${u.id}">${u.active?'Desactivar':'Activar'}</button>`:''}</div>`).join('')}</div>`}
function settings(){return head('Hacelo tuyo.','Ajustes visuales y exportación del trabajo.')+`<div class="panel settings"><div class="panel-body"><form id="settings-form"><label>Nombre del estudio</label><input name="name" required value="${esc(state.settings.name)}"><div class="form-grid"><div><label>Acento principal</label><input name="accent" type="color" value="${state.settings.accent}"></div><div><label>Acento secundario</label><input name="secondary" type="color" value="${state.settings.secondary}"></div></div><label>Foto de perfil · URL HTTPS (opcional)</label><input name="avatar" type="url" placeholder="https://…" value="${esc(state.settings.avatar)}"><p class="muted" style="margin-top:12px">Podés cambiar los colores y reemplazar las iniciales por tu foto.</p><div class="actions"><button class="btn lime">Guardar cambios</button></div></form><hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><h3>Una copia de tu trabajo</h3><p class="muted" style="margin:8px 0 15px">Exporta clientes, tareas, comentarios y actividad. No incluye contraseñas ni sesiones. Para restaurar todo el sistema, respaldá la base de datos del servidor.</p><button class="btn soft" data-action="export">Descargar exportación JSON</button></div></div>`}
function surface(){return view==='dashboard'?dashboard():['tasks','mine','content'].includes(view)?tasks():view==='calendar'?calendar():view==='clients'?clients():view==='team'&&admin()?team():view==='settings'&&admin()?settings():`<div class="portal-placeholder"><span class="badge purple">Segunda etapa</span><h2>Un espacio simple<br>para tus clientes.</h2><p>Chat, solicitudes, revisión de contenido y aprobaciones. Este portal todavía no está habilitado. Primero estamos organizando la operación del estudio.</p><p style="margin-top:20px">La futura cuenta de cada cliente deberá dar acceso únicamente a su información.</p></div>`}
function openModal(title,body){$('#modal').innerHTML=`<header class="modal-head"><h2>${title}</h2><button class="close" data-action="close" aria-label="Cerrar">×</button></header><div class="modal-body">${body}</div>`;if(!$('#modal').open)$('#modal').showModal()}
function close(){ $('#modal').close();focusId=null }
function formField(label,name,value='',type='text',extra=''){return `<div><label>${label}</label><input type="${type}" name="${name}" value="${esc(value)}" ${extra}></div>`}
function textArea(label,name,value=''){return `<div class="full"><label>${label}</label><textarea name="${name}">${esc(value)}</textarea></div>`}
function taskModal(taskid=null){
 const t=state.tasks.find(t=>t.id===taskid)||{title:'',kind:view==='content'?'Contenido':'Tarea',clientId:state.clients[0]?.id,assigneeId:state.users.find(u=>u.active)?.id,priority:'Planificable',status:'Pendiente',stage:'Idea',rounds:0,roundLimit:2,links:[]};
 if(!taskid&&!state.clients.length){notify('Primero creá un cliente.');clientModal();return}
 focusId=taskid;let body='';const lock=!admin()?'disabled':'';
 if(detailTab==='ficha'||!taskid)body=`<form id="task-form"><div class="form-grid">${formField('Título','title',t.title,'text','required maxlength="180"')}<div><label>Tipo</label><select name="kind">${opts(['Tarea','Contenido'],t.kind)}</select></div><div><label>Cliente</label><select name="clientId" ${lock}>${entityOpts(state.clients,t.clientId)}</select></div><div><label>Responsable</label><select name="assigneeId" ${lock}>${entityOpts(state.users.filter(u=>u.active||u.id===t.assigneeId),t.assigneeId)}</select></div><div><label>Estado de la tarea</label><select name="status">${opts(STATUS,t.status)}</select></div><div><label>Prioridad final · define administración</label><select name="priority" ${lock}>${opts(['Planificable','Próximo','Prioritario','Crítico'],t.priority)}</select></div>${formField('Fecha límite','due',t.due,'date',lock)}${formField('Fecha de publicación','publishDate',t.publishDate,'date',lock)}${textArea('Descripción / brief','description',t.description)}<div class="full"><label>Motivo de la prioridad</label><textarea name="priorityReason" ${lock}>${esc(t.priorityReason)}</textarea></div>${textArea('Si está bloqueada, ¿qué falta?','blocker',t.blocker)}<div><label>Etapa del contenido</label><select name="stage">${opts(STAGES,t.stage)}</select></div><div><label>Formato</label><select name="format">${opts(['Reel','Carrusel','Post','Historia','Video','Otro'],t.format||'Reel')}</select></div>${formField('Plataforma','platform',t.platform||'Instagram')}${formField('Rondas utilizadas','rounds',t.rounds,'number',`${lock} min="0" max="100"`)}${formField('Rondas incluidas','roundLimit',t.roundLimit,'number',`${lock} min="0" max="100"`)}${admin()?'<div><label>Excepción de correcciones</label><label style="font-weight:400"><input style="width:auto" type="checkbox" name="overrideRounds"> Aceptar rondas adicionales</label></div>':''}${textArea('Guion','script',t.script)}${textArea('Copy','copy',t.copy)}${textArea('Enlaces a materiales · uno por línea (Drive, video, diseño)','links',t.links.join('\n'))}</div><p class="muted" style="margin-top:15px">Se guardan enlaces, no archivos subidos. ${taskid?'Versión '+t.version:'Nueva tarea'}.</p><div class="actions">${taskid&&admin()?'<button type="button" class="btn danger" data-action="delete-task">Eliminar</button>':''}<button class="btn lime">Guardar tarea</button></div></form>`;
 else if(detailTab==='marca')body=`<h3 style="margin-top:20px">${esc(client(t.clientId).name)} · memoria de marca</h3><p class="prewrap" style="margin:20px 0">${esc(client(t.clientId).memory||'Sin memoria registrada todavía.')}</p><p class="muted">${esc(client(t.clientId).plan)}</p>`;
 else if(detailTab==='comentarios')body=`${state.comments.filter(c=>c.task_id===taskid).map(c=>`<div class="comment"><strong>${esc(c.author)}</strong> <small>${stamp(c.created)}</small><p>${esc(c.text)}</p></div>`).join('')||'<p class="empty">Todo el feedback, en este lugar.</p>'}<form id="comment-form"><label>Comentario interno</label><textarea name="text" required maxlength="4000" placeholder="Dejá una nota al equipo…"></textarea><div class="actions"><button class="btn lime">Agregar comentario</button></div></form>`;
 else body=state.activity.filter(c=>c.task_id===taskid).map(c=>`<div class="comment"><strong>${esc(c.text)}</strong><p>${esc(c.author)} · ${stamp(c.created)}</p></div>`).join('')||'<p class="empty">Sin actividad registrada.</p>';
 openModal(taskid?'Ficha de trabajo':'Nueva tarea',`${taskid?`<div class="modal-tabs">${[['ficha','Ficha'],['marca','Marca'],['comentarios','Comentarios'],['historial','Historial']].map(([key,label])=>`<button data-detail="${key}" class="${detailTab===key?'active':''}">${label}</button>`).join('')}</div>`:''}${body}`);
 if($('#task-form'))$('#task-form').onsubmit=async e=>{
  e.preventDefault();let fd=Object.fromEntries(new FormData(e.target)),d={...t,...fd};d.rounds=Number(d.rounds);d.roundLimit=Number(d.roundLimit);d.links=String(fd.links||'').split('\n').map(s=>s.trim()).filter(Boolean);d.overrideRounds=fd.overrideRounds==='on';
  if(['Prioritario','Crítico'].includes(d.priority)&&!d.priorityReason?.trim()){notify('Indicá el motivo de la prioridad.');return}if(d.status==='Bloqueada'&&!d.blocker?.trim()){notify('Indicá qué falta para continuar.');return}if(d.links.some(l=>!/^https?:\/\/[^\s]+$/i.test(l))){notify('Los enlaces deben empezar con http:// o https://.');return}if(d.rounds>d.roundLimit&&!d.overrideRounds){notify('Se requiere aceptar una excepción para agregar más correcciones.');return}
  await saving(e.target,()=>api('/api/tasks'+(taskid?'/'+taskid:''),taskid?'PATCH':'POST',d),()=>{close();notify('Tarea guardada.');refresh()});
 };
 if($('#comment-form'))$('#comment-form').onsubmit=async e=>{e.preventDefault();await saving(e.target,()=>api('/api/comments','POST',{taskId:taskid,text:new FormData(e.target).get('text')}),async()=>{await refresh(false);taskModal(taskid);notify('Comentario agregado.')})};
}
async function saving(form,fn,success){const b=form.querySelector('button[type="submit"],button:not([type])');if(b)b.disabled=true;try{await fn();await success()}catch(err){notify(err.message)}finally{if(b)b.disabled=false}}
function clientModal(clientid=null){
 const c=state.clients.find(c=>c.id===clientid)||{};
 if(!admin()){openModal(esc(c.name),`<p class="muted" style="margin:20px 0">${esc(c.plan)}</p><h3>Memoria de marca</h3><p class="prewrap" style="margin:18px 0">${esc(c.memory)}</p>${state.tasks.filter(t=>t.clientId===c.id).map(row).join('')}`);return}
 openModal(clientid?esc(c.name):'Nuevo cliente',`<form id="client-form"><div class="form-grid">${formField('Nombre del cliente','name',c.name,'text','required maxlength="120"')}${formField('Contacto','contact',c.contact)}${formField('Plan / servicio','plan',c.plan)}${formField('Inicio','startDate',c.startDate,'date')}${textArea('Memoria de marca · tono, diferenciales, ubicaciones, decisiones','memory',c.memory)}${textArea('Notas internas','notes',c.notes)}</div><div class="actions">${clientid?`<button type="button" class="btn soft" data-client-tasks="${clientid}">Ver tareas</button>`:''}<button class="btn lime">Guardar cliente</button></div></form>`);
 $('#client-form').onsubmit=async e=>{e.preventDefault();await saving(e.target,()=>api('/api/clients'+(clientid?'/'+clientid:''),clientid?'PATCH':'POST',Object.fromEntries(new FormData(e.target))),()=>{close();refresh();notify('Cliente guardado.')})};
}
function userModal(userId=null){const u=state.users.find(u=>u.id===userId);openModal(u?'Cambiar contraseña':'Nuevo integrante',`<form id="user-form">${u?'':formField('Nombre','name','','text','required')+formField('Email','email','','email','required')}${formField('Contraseña · mínimo 12 caracteres','password','','password','required minlength="12" autocomplete="new-password"')}<p class="notice">${DEMO?'La demo no crea accesos reales ni guarda esta contraseña.':'Cada integrante accede con su email. Compartí su contraseña de forma privada.'}</p><div class="actions"><button class="btn lime">${u?'Actualizar acceso':'Crear acceso'}</button></div></form>`);$('#user-form').onsubmit=async e=>{e.preventDefault();await saving(e.target,()=>api('/api/users'+(userId?'/'+userId:''),userId?'PATCH':'POST',Object.fromEntries(new FormData(e.target))),()=>{close();refresh();notify(DEMO?'Ejemplo actualizado.':'Acceso actualizado. Si cambiaste tu contraseña, volvé a ingresar.')})}}
async function runAction(action){
 if(action==='close'){close();return}if(action==='new-task'){detailTab='ficha';taskModal();return}if(action==='new-client'){clientModal();return}if(action==='new-user'){userModal();return}
 if(action==='clear-filters'){resetFilters();draw();return}
 if(action==='logout'){if(DEMO){notify('La demo no tiene sesiones reales.');return}await api('/api/logout','POST',{});state=null;clearInterval(poll);login();return}
 if(action==='reset-demo'){if(confirm('¿Restablecer los ejemplos? Se borrarán los cambios de esta demo.')){fullDemo=seed();saveDemo();draw()}return}
 if(action==='delete-task'){if(confirm('¿Eliminar esta tarea y sus comentarios?')){let t=state.tasks.find(t=>t.id===focusId);await api('/api/tasks/'+t.id,'DELETE',{version:t.version});close();await refresh();notify('Tarea eliminada.')}return}
 if(action==='export'){let d=await api('/api/export');if(DEMO){d=structuredClone(d);delete d.csrf;delete d.user;delete d.currentUser}const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`andrina-export-${today()}.json`;a.click();URL.revokeObjectURL(url);notify('Exportación descargada.')}
}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button,[data-task]');if(!b)return;
 try{
 if(b.dataset.action){await runAction(b.dataset.action);return}
 if(b.dataset.view){view=b.dataset.view;resetFilters();draw();return}
 if(b.dataset.task){detailTab='ficha';taskModal(b.dataset.task);return}
 if(b.dataset.client){clientModal(b.dataset.client);return}
 if(b.dataset.clientTasks){close();view='tasks';resetFilters();clientFilter=b.dataset.clientTasks;draw();return}
 if(b.dataset.display){display=b.dataset.display;$('#surface').innerHTML=surface();return}
 if(b.dataset.detail){detailTab=b.dataset.detail;taskModal(focusId);return}
 if(b.dataset.cal){cal=Number(b.dataset.cal)===0?new Date():new Date(cal.getFullYear(),cal.getMonth()+Number(b.dataset.cal),1);$('#surface').innerHTML=surface();return}
 if(b.dataset.stat){view=b.dataset.stat==='clients'?'clients':'tasks';resetFilters();statusFilter=b.dataset.stat==='review'?'En revisión':b.dataset.stat==='late'?'__late':'';display=b.dataset.stat==='late'?'list':display;draw();return}
 if(b.dataset.password){userModal(b.dataset.password);return}
 if(b.dataset.userToggle){let u=state.users.find(u=>u.id===b.dataset.userToggle);if(confirm(`${u.active?'Desactivar':'Activar'} el acceso de ${u.name}?`)){await api('/api/users/'+u.id,'PATCH',{active:!u.active});await refresh()}return}
 }catch(err){notify(err.message)}
});
document.addEventListener('keydown',e=>{if(e.target.matches('tr[data-task]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();detailTab='ficha';taskModal(e.target.dataset.task)}});
document.addEventListener('change',e=>{if(e.target.id==='client-filter')clientFilter=e.target.value;else if(e.target.id==='owner-filter')ownerFilter=e.target.value;else if(e.target.id==='status-filter')statusFilter=e.target.value;else return;$('#surface').innerHTML=surface()});
document.addEventListener('submit',async e=>{if(e.target.id!=='settings-form')return;e.preventDefault();await saving(e.target,()=>api('/api/settings','PATCH',Object.fromEntries(new FormData(e.target))),()=>{refresh();notify('Configuración actualizada.')})});
$('#modal').addEventListener('cancel',()=>{focusId=null});
function startPoll(){clearInterval(poll);poll=setInterval(()=>{if(!document.hidden&&!$('#modal').open&&state&&!['settings','clients','team'].includes(view))refresh().catch(()=>{});},30000)}
async function boot(){if(DEMO){try{fullDemo=JSON.parse(localStorage.getItem(STORE))||seed()}catch{fullDemo=seed()}state=demoState();draw();window.addEventListener('storage',e=>{if(e.key===STORE){try{fullDemo=JSON.parse(e.newValue)||seed();state=demoState();if(!$('#modal').open)draw()}catch{}}});return}try{await refresh();startPoll()}catch{login()}}
boot();
